# Generated by Django 5.1.5 on 2025-01-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
