# Generated by Django 5.1.5 on 2025-01-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_technician_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='password',
            field=models.CharField(default='default_password', max_length=255),
        ),
    ]
