# Generated by Django 5.1.5 on 2025-01-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_technician_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='plain_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technician',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
